"""empty message

Revision ID: 5b7c22765c49
Revises: 
Create Date: 2020-01-13 13:17:19.778566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b7c22765c49'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('USL', sa.String(), nullable=True),
    sa.Column('UCL', sa.String(), nullable=True),
    sa.Column('T', sa.String(), nullable=True),
    sa.Column('LCL', sa.String(), nullable=True),
    sa.Column('LSL', sa.String(), nullable=True),
    sa.Column('IP_address', sa.String(), nullable=True),
    sa.Column('IP_port', sa.String(), nullable=True),
    sa.Column('CSV_data', sa.String(), nullable=True),
    sa.Column('Room', sa.String(), nullable=True),
    sa.Column('Furnace', sa.String(), nullable=True),
    sa.Column('Pieces', sa.String(), nullable=True),
    sa.Column('MIN', sa.String(), nullable=True),
    sa.Column('MAX', sa.String(), nullable=True),
    sa.Column('Set', sa.String(), nullable=True),
    sa.Column('Platform', sa.String(), nullable=True),
    sa.Column('Pipe', sa.String(), nullable=True),
    sa.Column('Version', sa.String(), nullable=True),
    sa.Column('TestPoint', sa.String(), nullable=True),
    sa.Column('CSV_file', sa.String(), nullable=True),
    sa.Column('Excel_output', sa.String(), nullable=True),
    sa.Column('Break_points', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('only_pipe', sa.Integer(), nullable=True),
    sa.Column('is_use', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('config')
    # ### end Alembic commands ###
